version: '3.8'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin1234   # >= 8 ký tự
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:15
    container_name: documents-postgres
    environment:
      POSTGRES_DB: docsdb
      POSTGRES_USER: docs
      POSTGRES_PASSWORD: docs_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  minio_data:
  pgdata:
